// AUTO-GERADO — não editar à mão.
// 7 chefes × 3 fases × 8 direções = 168 sprites
export type SpriteDirection = 'south' | 'east' | 'north' | 'west' | 'south-east' | 'north-east' | 'north-west' | 'south-west'

export const BOSS_REGISTRY: Record<string, Record<number, Record<SpriteDirection, number>>> = {
  axis_velum: {
    1: {
      south: require('../../../assets/sprites/bosses/axis_velum/fase1/south.png'),
      east: require('../../../assets/sprites/bosses/axis_velum/fase1/east.png'),
      north: require('../../../assets/sprites/bosses/axis_velum/fase1/north.png'),
      west: require('../../../assets/sprites/bosses/axis_velum/fase1/west.png'),
      'south-east': require('../../../assets/sprites/bosses/axis_velum/fase1/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/axis_velum/fase1/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/axis_velum/fase1/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/axis_velum/fase1/south-west.png'),
    },
    2: {
      south: require('../../../assets/sprites/bosses/axis_velum/fase2/south.png'),
      east: require('../../../assets/sprites/bosses/axis_velum/fase2/east.png'),
      north: require('../../../assets/sprites/bosses/axis_velum/fase2/north.png'),
      west: require('../../../assets/sprites/bosses/axis_velum/fase2/west.png'),
      'south-east': require('../../../assets/sprites/bosses/axis_velum/fase2/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/axis_velum/fase2/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/axis_velum/fase2/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/axis_velum/fase2/south-west.png'),
    },
    3: {
      south: require('../../../assets/sprites/bosses/axis_velum/fase3/south.png'),
      east: require('../../../assets/sprites/bosses/axis_velum/fase3/east.png'),
      north: require('../../../assets/sprites/bosses/axis_velum/fase3/north.png'),
      west: require('../../../assets/sprites/bosses/axis_velum/fase3/west.png'),
      'south-east': require('../../../assets/sprites/bosses/axis_velum/fase3/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/axis_velum/fase3/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/axis_velum/fase3/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/axis_velum/fase3/south-west.png'),
    },
  },
  cinderfall_ignis: {
    1: {
      south: require('../../../assets/sprites/bosses/cinderfall_ignis/fase1/south.png'),
      east: require('../../../assets/sprites/bosses/cinderfall_ignis/fase1/east.png'),
      north: require('../../../assets/sprites/bosses/cinderfall_ignis/fase1/north.png'),
      west: require('../../../assets/sprites/bosses/cinderfall_ignis/fase1/west.png'),
      'south-east': require('../../../assets/sprites/bosses/cinderfall_ignis/fase1/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/cinderfall_ignis/fase1/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/cinderfall_ignis/fase1/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/cinderfall_ignis/fase1/south-west.png'),
    },
    2: {
      south: require('../../../assets/sprites/bosses/cinderfall_ignis/fase2/south.png'),
      east: require('../../../assets/sprites/bosses/cinderfall_ignis/fase2/east.png'),
      north: require('../../../assets/sprites/bosses/cinderfall_ignis/fase2/north.png'),
      west: require('../../../assets/sprites/bosses/cinderfall_ignis/fase2/west.png'),
      'south-east': require('../../../assets/sprites/bosses/cinderfall_ignis/fase2/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/cinderfall_ignis/fase2/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/cinderfall_ignis/fase2/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/cinderfall_ignis/fase2/south-west.png'),
    },
    3: {
      south: require('../../../assets/sprites/bosses/cinderfall_ignis/fase3/south.png'),
      east: require('../../../assets/sprites/bosses/cinderfall_ignis/fase3/east.png'),
      north: require('../../../assets/sprites/bosses/cinderfall_ignis/fase3/north.png'),
      west: require('../../../assets/sprites/bosses/cinderfall_ignis/fase3/west.png'),
      'south-east': require('../../../assets/sprites/bosses/cinderfall_ignis/fase3/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/cinderfall_ignis/fase3/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/cinderfall_ignis/fase3/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/cinderfall_ignis/fase3/south-west.png'),
    },
  },
  kethara_lithos: {
    1: {
      south: require('../../../assets/sprites/bosses/kethara_lithos/fase1/south.png'),
      east: require('../../../assets/sprites/bosses/kethara_lithos/fase1/east.png'),
      north: require('../../../assets/sprites/bosses/kethara_lithos/fase1/north.png'),
      west: require('../../../assets/sprites/bosses/kethara_lithos/fase1/west.png'),
      'south-east': require('../../../assets/sprites/bosses/kethara_lithos/fase1/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/kethara_lithos/fase1/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/kethara_lithos/fase1/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/kethara_lithos/fase1/south-west.png'),
    },
    2: {
      south: require('../../../assets/sprites/bosses/kethara_lithos/fase2/south.png'),
      east: require('../../../assets/sprites/bosses/kethara_lithos/fase2/east.png'),
      north: require('../../../assets/sprites/bosses/kethara_lithos/fase2/north.png'),
      west: require('../../../assets/sprites/bosses/kethara_lithos/fase2/west.png'),
      'south-east': require('../../../assets/sprites/bosses/kethara_lithos/fase2/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/kethara_lithos/fase2/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/kethara_lithos/fase2/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/kethara_lithos/fase2/south-west.png'),
    },
    3: {
      south: require('../../../assets/sprites/bosses/kethara_lithos/fase3/south.png'),
      east: require('../../../assets/sprites/bosses/kethara_lithos/fase3/east.png'),
      north: require('../../../assets/sprites/bosses/kethara_lithos/fase3/north.png'),
      west: require('../../../assets/sprites/bosses/kethara_lithos/fase3/west.png'),
      'south-east': require('../../../assets/sprites/bosses/kethara_lithos/fase3/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/kethara_lithos/fase3/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/kethara_lithos/fase3/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/kethara_lithos/fase3/south-west.png'),
    },
  },
  limiar_umbra: {
    1: {
      south: require('../../../assets/sprites/bosses/limiar_umbra/fase1/south.png'),
      east: require('../../../assets/sprites/bosses/limiar_umbra/fase1/east.png'),
      north: require('../../../assets/sprites/bosses/limiar_umbra/fase1/north.png'),
      west: require('../../../assets/sprites/bosses/limiar_umbra/fase1/west.png'),
      'south-east': require('../../../assets/sprites/bosses/limiar_umbra/fase1/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/limiar_umbra/fase1/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/limiar_umbra/fase1/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/limiar_umbra/fase1/south-west.png'),
    },
    2: {
      south: require('../../../assets/sprites/bosses/limiar_umbra/fase2/south.png'),
      east: require('../../../assets/sprites/bosses/limiar_umbra/fase2/east.png'),
      north: require('../../../assets/sprites/bosses/limiar_umbra/fase2/north.png'),
      west: require('../../../assets/sprites/bosses/limiar_umbra/fase2/west.png'),
      'south-east': require('../../../assets/sprites/bosses/limiar_umbra/fase2/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/limiar_umbra/fase2/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/limiar_umbra/fase2/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/limiar_umbra/fase2/south-west.png'),
    },
    3: {
      south: require('../../../assets/sprites/bosses/limiar_umbra/fase3/south.png'),
      east: require('../../../assets/sprites/bosses/limiar_umbra/fase3/east.png'),
      north: require('../../../assets/sprites/bosses/limiar_umbra/fase3/north.png'),
      west: require('../../../assets/sprites/bosses/limiar_umbra/fase3/west.png'),
      'south-east': require('../../../assets/sprites/bosses/limiar_umbra/fase3/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/limiar_umbra/fase3/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/limiar_umbra/fase3/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/limiar_umbra/fase3/south-west.png'),
    },
  },
  mnemos_echonis: {
    1: {
      south: require('../../../assets/sprites/bosses/mnemos_echonis/fase1/south.png'),
      east: require('../../../assets/sprites/bosses/mnemos_echonis/fase1/east.png'),
      north: require('../../../assets/sprites/bosses/mnemos_echonis/fase1/north.png'),
      west: require('../../../assets/sprites/bosses/mnemos_echonis/fase1/west.png'),
      'south-east': require('../../../assets/sprites/bosses/mnemos_echonis/fase1/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/mnemos_echonis/fase1/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/mnemos_echonis/fase1/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/mnemos_echonis/fase1/south-west.png'),
    },
    2: {
      south: require('../../../assets/sprites/bosses/mnemos_echonis/fase2/south.png'),
      east: require('../../../assets/sprites/bosses/mnemos_echonis/fase2/east.png'),
      north: require('../../../assets/sprites/bosses/mnemos_echonis/fase2/north.png'),
      west: require('../../../assets/sprites/bosses/mnemos_echonis/fase2/west.png'),
      'south-east': require('../../../assets/sprites/bosses/mnemos_echonis/fase2/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/mnemos_echonis/fase2/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/mnemos_echonis/fase2/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/mnemos_echonis/fase2/south-west.png'),
    },
    3: {
      south: require('../../../assets/sprites/bosses/mnemos_echonis/fase3/south.png'),
      east: require('../../../assets/sprites/bosses/mnemos_echonis/fase3/east.png'),
      north: require('../../../assets/sprites/bosses/mnemos_echonis/fase3/north.png'),
      west: require('../../../assets/sprites/bosses/mnemos_echonis/fase3/west.png'),
      'south-east': require('../../../assets/sprites/bosses/mnemos_echonis/fase3/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/mnemos_echonis/fase3/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/mnemos_echonis/fase3/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/mnemos_echonis/fase3/south-west.png'),
    },
  },
  venula_cruor: {
    1: {
      south: require('../../../assets/sprites/bosses/venula_cruor/fase1/south.png'),
      east: require('../../../assets/sprites/bosses/venula_cruor/fase1/east.png'),
      north: require('../../../assets/sprites/bosses/venula_cruor/fase1/north.png'),
      west: require('../../../assets/sprites/bosses/venula_cruor/fase1/west.png'),
      'south-east': require('../../../assets/sprites/bosses/venula_cruor/fase1/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/venula_cruor/fase1/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/venula_cruor/fase1/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/venula_cruor/fase1/south-west.png'),
    },
    2: {
      south: require('../../../assets/sprites/bosses/venula_cruor/fase2/south.png'),
      east: require('../../../assets/sprites/bosses/venula_cruor/fase2/east.png'),
      north: require('../../../assets/sprites/bosses/venula_cruor/fase2/north.png'),
      west: require('../../../assets/sprites/bosses/venula_cruor/fase2/west.png'),
      'south-east': require('../../../assets/sprites/bosses/venula_cruor/fase2/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/venula_cruor/fase2/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/venula_cruor/fase2/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/venula_cruor/fase2/south-west.png'),
    },
    3: {
      south: require('../../../assets/sprites/bosses/venula_cruor/fase3/south.png'),
      east: require('../../../assets/sprites/bosses/venula_cruor/fase3/east.png'),
      north: require('../../../assets/sprites/bosses/venula_cruor/fase3/north.png'),
      west: require('../../../assets/sprites/bosses/venula_cruor/fase3/west.png'),
      'south-east': require('../../../assets/sprites/bosses/venula_cruor/fase3/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/venula_cruor/fase3/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/venula_cruor/fase3/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/venula_cruor/fase3/south-west.png'),
    },
  },
  verdania_floris: {
    1: {
      south: require('../../../assets/sprites/bosses/verdania_floris/fase1/south.png'),
      east: require('../../../assets/sprites/bosses/verdania_floris/fase1/east.png'),
      north: require('../../../assets/sprites/bosses/verdania_floris/fase1/north.png'),
      west: require('../../../assets/sprites/bosses/verdania_floris/fase1/west.png'),
      'south-east': require('../../../assets/sprites/bosses/verdania_floris/fase1/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/verdania_floris/fase1/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/verdania_floris/fase1/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/verdania_floris/fase1/south-west.png'),
    },
    2: {
      south: require('../../../assets/sprites/bosses/verdania_floris/fase2/south.png'),
      east: require('../../../assets/sprites/bosses/verdania_floris/fase2/east.png'),
      north: require('../../../assets/sprites/bosses/verdania_floris/fase2/north.png'),
      west: require('../../../assets/sprites/bosses/verdania_floris/fase2/west.png'),
      'south-east': require('../../../assets/sprites/bosses/verdania_floris/fase2/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/verdania_floris/fase2/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/verdania_floris/fase2/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/verdania_floris/fase2/south-west.png'),
    },
    3: {
      south: require('../../../assets/sprites/bosses/verdania_floris/fase3/south.png'),
      east: require('../../../assets/sprites/bosses/verdania_floris/fase3/east.png'),
      north: require('../../../assets/sprites/bosses/verdania_floris/fase3/north.png'),
      west: require('../../../assets/sprites/bosses/verdania_floris/fase3/west.png'),
      'south-east': require('../../../assets/sprites/bosses/verdania_floris/fase3/south-east.png'),
      'north-east': require('../../../assets/sprites/bosses/verdania_floris/fase3/north-east.png'),
      'north-west': require('../../../assets/sprites/bosses/verdania_floris/fase3/north-west.png'),
      'south-west': require('../../../assets/sprites/bosses/verdania_floris/fase3/south-west.png'),
    },
  },
}
