// AUTO-GERADO — não editar à mão. Regenerar com o script de geração de registry.
// Sprites de herói PixelLab. require() exige string literal, por isso o mapa é estático.
//
export type SpriteDirection =
  | 'south' | 'east' | 'north' | 'west'
  | 'south-east' | 'north-east' | 'north-west' | 'south-west'

export type SpriteTierMap = Partial<Record<string, Record<SpriteDirection, number>>>

// [folder][build][tier][direction] = asset module (require)
export const SPRITE_REGISTRY: Record<string, Record<string, SpriteTierMap>> = {
  arauto: {
    arauto: {
      comum: {
        'south': require('../../../assets/sprites/heroes/arauto/arauto/comum/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/arauto/comum/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/arauto/comum/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/arauto/comum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/arauto/comum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/arauto/comum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/arauto/comum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/arauto/comum/south-west.png'),
      },
      incomum: {
        'south': require('../../../assets/sprites/heroes/arauto/arauto/incomum/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/arauto/incomum/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/arauto/incomum/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/arauto/incomum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/arauto/incomum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/arauto/incomum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/arauto/incomum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/arauto/incomum/south-west.png'),
      },
      raro: {
        'south': require('../../../assets/sprites/heroes/arauto/arauto/raro/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/arauto/raro/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/arauto/raro/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/arauto/raro/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/arauto/raro/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/arauto/raro/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/arauto/raro/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/arauto/raro/south-west.png'),
      },
      epico: {
        'south': require('../../../assets/sprites/heroes/arauto/arauto/epico/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/arauto/epico/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/arauto/epico/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/arauto/epico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/arauto/epico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/arauto/epico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/arauto/epico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/arauto/epico/south-west.png'),
      },
      lendario: {
        'south': require('../../../assets/sprites/heroes/arauto/arauto/lendario/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/arauto/lendario/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/arauto/lendario/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/arauto/lendario/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/arauto/lendario/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/arauto/lendario/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/arauto/lendario/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/arauto/lendario/south-west.png'),
      },
      unico: {
        'south': require('../../../assets/sprites/heroes/arauto/arauto/unico/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/arauto/unico/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/arauto/unico/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/arauto/unico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/arauto/unico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/arauto/unico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/arauto/unico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/arauto/unico/south-west.png'),
      },
    },
    corneiro: {
      comum: {
        'south': require('../../../assets/sprites/heroes/arauto/corneiro/comum/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/corneiro/comum/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/corneiro/comum/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/corneiro/comum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/corneiro/comum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/corneiro/comum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/corneiro/comum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/corneiro/comum/south-west.png'),
      },
      incomum: {
        'south': require('../../../assets/sprites/heroes/arauto/corneiro/incomum/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/corneiro/incomum/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/corneiro/incomum/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/corneiro/incomum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/corneiro/incomum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/corneiro/incomum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/corneiro/incomum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/corneiro/incomum/south-west.png'),
      },
      raro: {
        'south': require('../../../assets/sprites/heroes/arauto/corneiro/raro/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/corneiro/raro/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/corneiro/raro/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/corneiro/raro/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/corneiro/raro/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/corneiro/raro/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/corneiro/raro/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/corneiro/raro/south-west.png'),
      },
      epico: {
        'south': require('../../../assets/sprites/heroes/arauto/corneiro/epico/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/corneiro/epico/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/corneiro/epico/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/corneiro/epico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/corneiro/epico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/corneiro/epico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/corneiro/epico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/corneiro/epico/south-west.png'),
      },
      lendario: {
        'south': require('../../../assets/sprites/heroes/arauto/corneiro/lendario/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/corneiro/lendario/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/corneiro/lendario/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/corneiro/lendario/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/corneiro/lendario/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/corneiro/lendario/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/corneiro/lendario/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/corneiro/lendario/south-west.png'),
      },
      unico: {
        'south': require('../../../assets/sprites/heroes/arauto/corneiro/unico/south.png'),
        'east': require('../../../assets/sprites/heroes/arauto/corneiro/unico/east.png'),
        'north': require('../../../assets/sprites/heroes/arauto/corneiro/unico/north.png'),
        'west': require('../../../assets/sprites/heroes/arauto/corneiro/unico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/arauto/corneiro/unico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/arauto/corneiro/unico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/arauto/corneiro/unico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/arauto/corneiro/unico/south-west.png'),
      },
    },
  },
  destruidor: {
    fragmentador: {
      comum: {
        'south': require('../../../assets/sprites/heroes/destruidor/fragmentador/comum/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/fragmentador/comum/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/fragmentador/comum/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/fragmentador/comum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/comum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/comum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/comum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/comum/south-west.png'),
      },
      incomum: {
        'south': require('../../../assets/sprites/heroes/destruidor/fragmentador/incomum/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/fragmentador/incomum/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/fragmentador/incomum/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/fragmentador/incomum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/incomum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/incomum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/incomum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/incomum/south-west.png'),
      },
      raro: {
        'south': require('../../../assets/sprites/heroes/destruidor/fragmentador/raro/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/fragmentador/raro/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/fragmentador/raro/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/fragmentador/raro/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/raro/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/raro/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/raro/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/raro/south-west.png'),
      },
      epico: {
        'south': require('../../../assets/sprites/heroes/destruidor/fragmentador/epico/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/fragmentador/epico/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/fragmentador/epico/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/fragmentador/epico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/epico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/epico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/epico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/epico/south-west.png'),
      },
      lendario: {
        'south': require('../../../assets/sprites/heroes/destruidor/fragmentador/lendario/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/fragmentador/lendario/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/fragmentador/lendario/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/fragmentador/lendario/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/lendario/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/lendario/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/lendario/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/lendario/south-west.png'),
      },
      unico: {
        'south': require('../../../assets/sprites/heroes/destruidor/fragmentador/unico/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/fragmentador/unico/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/fragmentador/unico/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/fragmentador/unico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/unico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/fragmentador/unico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/unico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/fragmentador/unico/south-west.png'),
      },
    },
    reaver: {
      comum: {
        'south': require('../../../assets/sprites/heroes/destruidor/reaver/comum/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/reaver/comum/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/reaver/comum/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/reaver/comum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/reaver/comum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/reaver/comum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/reaver/comum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/reaver/comum/south-west.png'),
      },
      incomum: {
        'south': require('../../../assets/sprites/heroes/destruidor/reaver/incomum/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/reaver/incomum/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/reaver/incomum/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/reaver/incomum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/reaver/incomum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/reaver/incomum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/reaver/incomum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/reaver/incomum/south-west.png'),
      },
      raro: {
        'south': require('../../../assets/sprites/heroes/destruidor/reaver/raro/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/reaver/raro/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/reaver/raro/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/reaver/raro/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/reaver/raro/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/reaver/raro/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/reaver/raro/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/reaver/raro/south-west.png'),
      },
      epico: {
        'south': require('../../../assets/sprites/heroes/destruidor/reaver/epico/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/reaver/epico/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/reaver/epico/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/reaver/epico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/reaver/epico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/reaver/epico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/reaver/epico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/reaver/epico/south-west.png'),
      },
      lendario: {
        'south': require('../../../assets/sprites/heroes/destruidor/reaver/lendario/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/reaver/lendario/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/reaver/lendario/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/reaver/lendario/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/reaver/lendario/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/reaver/lendario/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/reaver/lendario/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/reaver/lendario/south-west.png'),
      },
      unico: {
        'south': require('../../../assets/sprites/heroes/destruidor/reaver/unico/south.png'),
        'east': require('../../../assets/sprites/heroes/destruidor/reaver/unico/east.png'),
        'north': require('../../../assets/sprites/heroes/destruidor/reaver/unico/north.png'),
        'west': require('../../../assets/sprites/heroes/destruidor/reaver/unico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/destruidor/reaver/unico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/destruidor/reaver/unico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/destruidor/reaver/unico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/destruidor/reaver/unico/south-west.png'),
      },
    },
  },
  guardiao: {
    guardiao: {
      comum: {
        'south': require('../../../assets/sprites/heroes/guardiao/guardiao/comum/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/guardiao/comum/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/guardiao/comum/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/guardiao/comum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/guardiao/comum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/guardiao/comum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/guardiao/comum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/guardiao/comum/south-west.png'),
      },
      incomum: {
        'south': require('../../../assets/sprites/heroes/guardiao/guardiao/incomum/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/guardiao/incomum/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/guardiao/incomum/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/guardiao/incomum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/guardiao/incomum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/guardiao/incomum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/guardiao/incomum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/guardiao/incomum/south-west.png'),
      },
      raro: {
        'south': require('../../../assets/sprites/heroes/guardiao/guardiao/raro/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/guardiao/raro/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/guardiao/raro/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/guardiao/raro/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/guardiao/raro/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/guardiao/raro/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/guardiao/raro/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/guardiao/raro/south-west.png'),
      },
      epico: {
        'south': require('../../../assets/sprites/heroes/guardiao/guardiao/epico/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/guardiao/epico/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/guardiao/epico/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/guardiao/epico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/guardiao/epico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/guardiao/epico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/guardiao/epico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/guardiao/epico/south-west.png'),
      },
      lendario: {
        'south': require('../../../assets/sprites/heroes/guardiao/guardiao/lendario/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/guardiao/lendario/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/guardiao/lendario/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/guardiao/lendario/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/guardiao/lendario/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/guardiao/lendario/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/guardiao/lendario/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/guardiao/lendario/south-west.png'),
      },
      unico: {
        'south': require('../../../assets/sprites/heroes/guardiao/guardiao/unico/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/guardiao/unico/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/guardiao/unico/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/guardiao/unico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/guardiao/unico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/guardiao/unico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/guardiao/unico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/guardiao/unico/south-west.png'),
      },
    },
    sentinela: {
      comum: {
        'south': require('../../../assets/sprites/heroes/guardiao/sentinela/comum/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/sentinela/comum/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/sentinela/comum/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/sentinela/comum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/sentinela/comum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/sentinela/comum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/sentinela/comum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/sentinela/comum/south-west.png'),
      },
      incomum: {
        'south': require('../../../assets/sprites/heroes/guardiao/sentinela/incomum/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/sentinela/incomum/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/sentinela/incomum/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/sentinela/incomum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/sentinela/incomum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/sentinela/incomum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/sentinela/incomum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/sentinela/incomum/south-west.png'),
      },
      raro: {
        'south': require('../../../assets/sprites/heroes/guardiao/sentinela/raro/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/sentinela/raro/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/sentinela/raro/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/sentinela/raro/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/sentinela/raro/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/sentinela/raro/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/sentinela/raro/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/sentinela/raro/south-west.png'),
      },
      epico: {
        'south': require('../../../assets/sprites/heroes/guardiao/sentinela/epico/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/sentinela/epico/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/sentinela/epico/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/sentinela/epico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/sentinela/epico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/sentinela/epico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/sentinela/epico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/sentinela/epico/south-west.png'),
      },
      lendario: {
        'south': require('../../../assets/sprites/heroes/guardiao/sentinela/lendario/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/sentinela/lendario/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/sentinela/lendario/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/sentinela/lendario/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/sentinela/lendario/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/sentinela/lendario/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/sentinela/lendario/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/sentinela/lendario/south-west.png'),
      },
      unico: {
        'south': require('../../../assets/sprites/heroes/guardiao/sentinela/unico/south.png'),
        'east': require('../../../assets/sprites/heroes/guardiao/sentinela/unico/east.png'),
        'north': require('../../../assets/sprites/heroes/guardiao/sentinela/unico/north.png'),
        'west': require('../../../assets/sprites/heroes/guardiao/sentinela/unico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/guardiao/sentinela/unico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/guardiao/sentinela/unico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/guardiao/sentinela/unico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/guardiao/sentinela/unico/south-west.png'),
      },
    },
  },
  invocador: {
    anciao: {
      comum: {
        'south': require('../../../assets/sprites/heroes/invocador/anciao/comum/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/anciao/comum/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/anciao/comum/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/anciao/comum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/anciao/comum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/anciao/comum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/anciao/comum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/anciao/comum/south-west.png'),
      },
      incomum: {
        'south': require('../../../assets/sprites/heroes/invocador/anciao/incomum/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/anciao/incomum/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/anciao/incomum/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/anciao/incomum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/anciao/incomum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/anciao/incomum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/anciao/incomum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/anciao/incomum/south-west.png'),
      },
      raro: {
        'south': require('../../../assets/sprites/heroes/invocador/anciao/raro/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/anciao/raro/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/anciao/raro/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/anciao/raro/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/anciao/raro/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/anciao/raro/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/anciao/raro/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/anciao/raro/south-west.png'),
      },
      epico: {
        'south': require('../../../assets/sprites/heroes/invocador/anciao/epico/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/anciao/epico/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/anciao/epico/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/anciao/epico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/anciao/epico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/anciao/epico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/anciao/epico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/anciao/epico/south-west.png'),
      },
      lendario: {
        'south': require('../../../assets/sprites/heroes/invocador/anciao/lendario/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/anciao/lendario/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/anciao/lendario/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/anciao/lendario/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/anciao/lendario/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/anciao/lendario/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/anciao/lendario/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/anciao/lendario/south-west.png'),
      },
      unico: {
        'south': require('../../../assets/sprites/heroes/invocador/anciao/unico/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/anciao/unico/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/anciao/unico/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/anciao/unico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/anciao/unico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/anciao/unico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/anciao/unico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/anciao/unico/south-west.png'),
      },
    },
    invocador: {
      comum: {
        'south': require('../../../assets/sprites/heroes/invocador/invocador/comum/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/invocador/comum/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/invocador/comum/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/invocador/comum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/invocador/comum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/invocador/comum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/invocador/comum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/invocador/comum/south-west.png'),
      },
      incomum: {
        'south': require('../../../assets/sprites/heroes/invocador/invocador/incomum/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/invocador/incomum/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/invocador/incomum/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/invocador/incomum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/invocador/incomum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/invocador/incomum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/invocador/incomum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/invocador/incomum/south-west.png'),
      },
      raro: {
        'south': require('../../../assets/sprites/heroes/invocador/invocador/raro/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/invocador/raro/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/invocador/raro/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/invocador/raro/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/invocador/raro/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/invocador/raro/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/invocador/raro/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/invocador/raro/south-west.png'),
      },
      epico: {
        'south': require('../../../assets/sprites/heroes/invocador/invocador/epico/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/invocador/epico/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/invocador/epico/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/invocador/epico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/invocador/epico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/invocador/epico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/invocador/epico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/invocador/epico/south-west.png'),
      },
      lendario: {
        'south': require('../../../assets/sprites/heroes/invocador/invocador/lendario/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/invocador/lendario/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/invocador/lendario/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/invocador/lendario/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/invocador/lendario/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/invocador/lendario/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/invocador/lendario/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/invocador/lendario/south-west.png'),
      },
      unico: {
        'south': require('../../../assets/sprites/heroes/invocador/invocador/unico/south.png'),
        'east': require('../../../assets/sprites/heroes/invocador/invocador/unico/east.png'),
        'north': require('../../../assets/sprites/heroes/invocador/invocador/unico/north.png'),
        'west': require('../../../assets/sprites/heroes/invocador/invocador/unico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/invocador/invocador/unico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/invocador/invocador/unico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/invocador/invocador/unico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/invocador/invocador/unico/south-west.png'),
      },
    },
  },
  trickster: {
    cacador: {
      comum: {
        'south': require('../../../assets/sprites/heroes/trickster/cacador/comum/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/cacador/comum/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/cacador/comum/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/cacador/comum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/cacador/comum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/cacador/comum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/cacador/comum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/cacador/comum/south-west.png'),
      },
      incomum: {
        'south': require('../../../assets/sprites/heroes/trickster/cacador/incomum/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/cacador/incomum/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/cacador/incomum/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/cacador/incomum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/cacador/incomum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/cacador/incomum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/cacador/incomum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/cacador/incomum/south-west.png'),
      },
      raro: {
        'south': require('../../../assets/sprites/heroes/trickster/cacador/raro/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/cacador/raro/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/cacador/raro/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/cacador/raro/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/cacador/raro/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/cacador/raro/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/cacador/raro/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/cacador/raro/south-west.png'),
      },
      epico: {
        'south': require('../../../assets/sprites/heroes/trickster/cacador/epico/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/cacador/epico/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/cacador/epico/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/cacador/epico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/cacador/epico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/cacador/epico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/cacador/epico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/cacador/epico/south-west.png'),
      },
      lendario: {
        'south': require('../../../assets/sprites/heroes/trickster/cacador/lendario/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/cacador/lendario/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/cacador/lendario/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/cacador/lendario/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/cacador/lendario/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/cacador/lendario/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/cacador/lendario/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/cacador/lendario/south-west.png'),
      },
      unico: {
        'south': require('../../../assets/sprites/heroes/trickster/cacador/unico/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/cacador/unico/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/cacador/unico/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/cacador/unico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/cacador/unico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/cacador/unico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/cacador/unico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/cacador/unico/south-west.png'),
      },
    },
    vidente: {
      comum: {
        'south': require('../../../assets/sprites/heroes/trickster/vidente/comum/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/vidente/comum/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/vidente/comum/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/vidente/comum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/vidente/comum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/vidente/comum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/vidente/comum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/vidente/comum/south-west.png'),
      },
      incomum: {
        'south': require('../../../assets/sprites/heroes/trickster/vidente/incomum/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/vidente/incomum/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/vidente/incomum/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/vidente/incomum/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/vidente/incomum/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/vidente/incomum/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/vidente/incomum/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/vidente/incomum/south-west.png'),
      },
      raro: {
        'south': require('../../../assets/sprites/heroes/trickster/vidente/raro/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/vidente/raro/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/vidente/raro/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/vidente/raro/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/vidente/raro/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/vidente/raro/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/vidente/raro/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/vidente/raro/south-west.png'),
      },
      epico: {
        'south': require('../../../assets/sprites/heroes/trickster/vidente/epico/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/vidente/epico/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/vidente/epico/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/vidente/epico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/vidente/epico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/vidente/epico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/vidente/epico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/vidente/epico/south-west.png'),
      },
      lendario: {
        'south': require('../../../assets/sprites/heroes/trickster/vidente/lendario/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/vidente/lendario/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/vidente/lendario/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/vidente/lendario/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/vidente/lendario/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/vidente/lendario/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/vidente/lendario/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/vidente/lendario/south-west.png'),
      },
      unico: {
        'south': require('../../../assets/sprites/heroes/trickster/vidente/unico/south.png'),
        'east': require('../../../assets/sprites/heroes/trickster/vidente/unico/east.png'),
        'north': require('../../../assets/sprites/heroes/trickster/vidente/unico/north.png'),
        'west': require('../../../assets/sprites/heroes/trickster/vidente/unico/west.png'),
        'south-east': require('../../../assets/sprites/heroes/trickster/vidente/unico/south-east.png'),
        'north-east': require('../../../assets/sprites/heroes/trickster/vidente/unico/north-east.png'),
        'north-west': require('../../../assets/sprites/heroes/trickster/vidente/unico/north-west.png'),
        'south-west': require('../../../assets/sprites/heroes/trickster/vidente/unico/south-west.png'),
      },
    },
  },
}
